package org.telegrambot.convertio.occ.bot.entities;

public enum State {
    TEST,
    ALL, NONE, CANCEL,
    SETTINGS, INFO,
    CURRENCIES_INFO,
    HELP, LANGUAGE, ACCOUNT, START,
    DEALS, DEALS_LIST, NEW_DEAL_START,
    // posts
    ADS,
    SET_CHANNEL_LINK_TO_SELL,
    SET_CHANNEL_NAME_TO_SELL,
    SET_CHANNEL_CURRENCY_TO_SELL,
    SET_CHANNEL_COST_TO_SELL,
    SET_CHANNEL_TAGS_TO_SELL,
    SET_CHANNEL_SUBSCRIBERS_TO_SELL,
    SET_CHANNEL_POST_VIEWS_TO_SELL,
    SET_AMOUNT_OF_SUBSCRIBERS,
    SET_CHANNEL_TYPE_OF_MONETIZATION,
    CONFIRM_PLACE_AD,
    SET_CHANNEL_MONETIZATION_INFO,
    SET_CHANNEL_INCOME_INFO,
    SET_CHANNEL_ADDITIONAL_INFO,
    SET_CHANNEL_CONTACT_INFO,
    ALL_ADS, FOUND_ADS, MY_AD,
    SEARCH_CATEGORIES_CHOOSE,
    SET_SEARCH_CHANNEL_TITLE,
    SET_SEARCH_CHANNEL_DATE,
    SET_SEARCH_CHANNEL_SELLER,
    SET_SEARCH_CHANNEL_COST,
    SET_SEARCH_CHANNEL_SUBSCRIBERS,
    SET_SEARCH_CHANNEL_VIEWS,
    SET_SEARCH_CHANNEL_TAGS,
    CONFIRM_AD_DELETE,
    CONFIRM_AD_UPDATE,
    CHOOSE_EDIT_AD_FIELDS,
    EDIT_CHANNEL_AD_COST,
    EDIT_CHANNEL_AD_CONTACT,
    EDIT_CHANNEL_AD_DESCRIPTION,
    EDIT_CHANNEL_AD_MONETIZATION,
    EDIT_CHANNEL_AD_SUBSCRIBERS,
    EDIT_CHANNEL_AD_VIEWS,
    EDIT_CHANNEL_AD_TAGS,
    CONFIRM_EDIT_AD,
    CANCEL_EDIT_AD,

    // deals
    CHOSEN_DEAL, CONFIRM_DELETE_CHOSEN_DEAL,
    // trade
    FOUND_USER, TRADE,
    SET_TRADE_CURRENCY, SET_TRADE_SUM, SET_TRADE_CHANNEL,
    ADD_BOT_TO_CHANNEL, TRANSFER_CHANNEL, APPROVE_DEAL_START,
    CONFIRM_THE_DEAL, FROZEN_DEAL,
    // payments
    //    -- withdraw
    CHOOSE_CURRENCY_WITHDRAW, CHOOSE_CURRENCY_RECEIVE,
    CHOOSE_PAYWAY_WITHDRAW, SET_AMOUNT_TO_RECEIVE,
    SET_REQUISITES, APPROVE_WITHDRAWAL,
    //    -- replenish
    CHOOSE_CURRENCY_REPLENISH, CHOOSE_PAYWAY_REPLENISH,
    SET_REPLENISH_AMOUNT, AWAIT_REPLENISH_APPROVAL, PAYING_PROCESS,
    REPLENISH_CRYPTO_WALLET,



    // formats
    SEARCH_FORMAT, CATEGORY_LIST, FORMAT_LIST, FORMAT_WRITABLE_TYPES,

    // convert
    CHOOSE_FORMAT_TO_CONVERT,


}
